name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ingore:
        - '**.md'
  pull_request:
    branches: [ main ]
    paths-ingore:
        - '**.md'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose up -d --build
    - name: Run pytest
      run: docker-compose exec -T web pytest .