name: Python package

on: [push]

jobs:
        build:
        runs-on: ubuntu-latest
        strategy:
                matrix:
                python-version: ["3.10", "3.11"]

        steps:
                - uses: actions/checkout@v3
                - name: Install hatch
                  run: pipx install hatch
                - name: Setup Python ${{ matrix.python-version }}
                  uses: actions/setup-python@v4
                  with:
                          python-version: ${{ matrix.python-version }}
                          cache: "hatch"
                - name: Install dependencies
                  run: hatch shell
                - name: Test with pytest
                  run: hatch run cov
